preset: recommended
risky: true
enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow
  - binary_operator_spaces
  - blank_line_after_namespace
  - blank_line_after_opening_tag
  - blank_line_before_return
  - braces

